version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dudemy-postgres
    environment:
      POSTGRES_DB: dudemy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dudemy-postgres-data:/var/lib/postgresql/data

volumes:
  dudemy-postgres-data:
