spring:
  application:
    name: dudemy
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dudemy
    username: postgres
    password: root
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  flyway:
    url: jdbc:postgresql://localhost:5432/dudemy
    user: postgres
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
    createSchemas: true